[build-system]
requires = ["setuptools>=40.8.0,!=51.1.0.post20201221", 'pybind11>=2.5', "wheel", "cmake", "conan>=1.51"]
build-backend = "builders.local_backend"
backend-path = ["."]

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
    "tests"
 ]
addopts = "--verbose"
markers =[
    "integration"
]
norecursedirs = [
    "features",
    "build"
]
junit_logging = "all"
junit_log_passing_tests = true
junit_family="xunit2"
bdd_features_base_dir = "tests/features/"

[tool.pylint.MASTER]
init-hook="sys.path.append('.')"

[tool.cibuildwheel]
test-requires = "pytest"
test-command = "pytest {project}/tests"
manylinux-x86_64-image = "manylinux2014"
build-frontend = "build"
skip = [
    "cp36-*",
    "cp37-macosx_*",
    "cp311-*",
    "pp*",
    "*-win32",
    "*-musllinux*",
    "*-manylinux_i686"
]
build-verbosity = 1
environment-pass = ["CONAN_COMPILER_VERSION"]

[tool.cibuildwheel.windows]
before-all = [
    "pip install wheel",
    "pip install conan cmake ninja",
    "echo 'Creating new 'profile'",
    "conan profile new C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\conan\\profiles\\default --detect --force",
    "echo 'updating 'profile'",
    "conan profile update settings.compiler.version=%CONAN_COMPILER_VERSION% C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\conan\\profiles\\default",
    "conan install ./ --build missing"
]
environment-pass = ["TEMP"]
[tool.cibuildwheel.windows.environment]
CONAN_USER_HOME="C:/Users/RUNNER~1/AppData/Local/Temp/conan"
CONAN_DEFAULT_PROFILE_PATH="C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\conan\\profiles\\default"


[tool.cibuildwheel.macos]
before-all = [
    "pip3 install conan cmake ninja",
    "conan profile new /tmp/conan/.conan/profiles/default --detect --force",
    "conan profile update settings.compiler.version=$CONAN_COMPILER_VERSION /tmp/conan/.conan/profiles/default",
    "conan install ./ --build missing"
]
repair-wheel-command = [
  "delocate-listdeps {wheel}",
  "delocate-wheel --require-archs {delocate_archs} -w {dest_dir} {wheel}",
]

[tool.cibuildwheel.macos.environment]
CONAN_USER_HOME="/tmp/conan"
CONAN_DEFAULT_PROFILE_PATH="/tmp/conan/.conan/profiles/default"


[tool.cibuildwheel.linux]
repair-wheel-command = "auditwheel repair -w {dest_dir} {wheel}"
before-all = [
    "pip3 install conan cmake ninja",
    "conan profile new /tmp/conan/.conan/profiles/default --detect",
    "conan install ./ --build missing --build tesseract"

]

[tool.cibuildwheel.linux.environment]
CONAN_USER_HOME="/tmp/conan"
CONAN_DEFAULT_PROFILE_PATH="/tmp/conan/.conan/profiles/default"

