[build-system]
requires = ["setuptools>=40.8.0,!=51.1.0.post20201221", 'pybind11>=2.5', "wheel", "cmake", "conan>=1.51"]
build-backend = "builders.local_backend"
backend-path = ["."]

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
    "tests"
 ]
addopts = "--verbose --capture=tee-sys"
markers =[
    "integration"
]
norecursedirs = [
    "features",
    "build"
]
junit_logging = "all"
junit_log_passing_tests = true
junit_family="xunit2"
bdd_features_base_dir = "tests/features/"

[tool.pylint.MASTER]
init-hook="sys.path.append('.')"
