[build-system]
requires = ["setuptools>=40.8.0,!=51.1.0.post20201221", 'pybind11~=2.10.1', "wheel", "cmake", "conan>=1.53,!=1.55.0"]
build-backend = "builders.local_backend"
backend-path = ["."]

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
    "tests"
 ]
addopts = "--verbose"
markers =[
    "integration"
]
norecursedirs = [
    "features",
    "build"
]
junit_logging = "all"
junit_log_passing_tests = true
junit_family="xunit2"
bdd_features_base_dir = "tests/features/"

[tool.pylint.MASTER]
init-hook="sys.path.append('.')"

[tool.cibuildwheel]
test-requires = "pytest"
test-command = "pytest {project}/tests"
manylinux-x86_64-image = "manylinux2014"
build-frontend = "build"
skip = [
    "cp36-*",
    "cp37-macosx_*",
    "pp*",
    "*-win32",
    "*-musllinux*",
    "*-manylinux_i686"
]
build-verbosity = 1
environment-pass = ["CONAN_COMPILER_LIBCXX", "CONAN_COMPILER_VERSION", "CONAN_USER_HOME"]

[tool.cibuildwheel.windows]
before-all = [
    "pip install wheel",
    "pip install conan cmake ninja",
    "conan profile new default --detect --force",
    "conan profile update settings.compiler.version=%CONAN_COMPILER_VERSION% default",
    "conan install ./ --build missing",
]
[tool.cibuildwheel.windows.environment]
CONAN_USER_HOME="$TEMP/conan"

[tool.cibuildwheel.macos]
before-all = [
    "pip3 install 'conan>=1.53' cmake ninja",
    "conan profile new $ENVTMPDIR/.conan/profiles/default --detect --force",
    "if [ -z \"$CONAN_COMPILER_VERSION\" ]; then : ; else conan profile update settings.compiler.version=$CONAN_COMPILER_VERSION default; fi",
    "conan install ./ --build missing --install-folder=$CONAN_BUILD_INFO_DIR"
]
environment-pass = ["CONAN_COMPILER_VERSION", "CONAN_USER_HOME"]
repair-wheel-command = [
    "delocate-wheel --version",
    "delocate-listdeps {wheel}",
    "delocate-wheel --require-archs {delocate_archs} -w {dest_dir} -v {wheel}",
]

[tool.cibuildwheel.macos.environment]
ENVTMPDIR="/tmp/ciwheelbuilder/uiucprescon_ocr"
CONAN_USER_HOME="/tmp/ciwheelbuilder/uiucprescon_ocr"
CONAN_DEFAULT_PROFILE_PATH="/tmp/ciwheelbuilder/uiucprescon_ocr/.conan/profiles/default"
CONAN_BUILD_INFO_DIR="/tmp/ciwheelbuilder/uiucprescon_ocr/build/"


[tool.cibuildwheel.linux]
repair-wheel-command = "auditwheel repair -w {dest_dir} {wheel}"
before-all = [
    "cc --version", "cc -dumpfullversion -dumpversion",
    'pip3 install "conan>=1.53,!=1.55.0" cmake ninja',
    "conan profile new /tmp/ciwheelbuilder/uiucprescon_ocr/.conan/profiles/default --detect",
    "if [ -z \"$CONAN_COMPILER_LIBCXX\" ]; then : ; else conan profile update settings.compiler.libcxx=$CONAN_COMPILER_LIBCXX default; fi",
    "if [ -z \"$CONAN_COMPILER_VERSION\" ]; then : ; else conan profile update settings.compiler.version=$CONAN_COMPILER_VERSION default; fi",
    "conan profile show default",
    "conan install ./ --build missing",

]
[tool.cibuildwheel.linux.environment]
CONAN_USER_HOME="/tmp/ciwheelbuilder/uiucprescon_ocr"
CONAN_DEFAULT_PROFILE_PATH="/tmp/ciwheelbuilder/uiucprescon_ocr/.conan/profiles/default"
CONAN_BUILD_INFO_DIR="/tmp/ciwheelbuilder/uiucprescon_ocr/build/"
PYTHONFAULTHANDLER="True"
#
[localbuilder]
conanfile = 'conanfile.py'

#[localbuilder.linux]
#conan_options = ['tesseract:shared=True']
[localbuilder.win32]
conan_options = ['tesseract:shared=True']

[tool.pylint]
extension-pkg-allow-list="uiucprescon.ocr.tesseractwrap"
