[build-system]
requires = [
    "setuptools>=61.0",
    'wheel',
    'conan<2.0',
    'uiucprescon.build @ git+https://github.com/UIUCLibrary/uiucprescon_build.git@v0.1.0'
]
build-backend = "uiucprescon.build"

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
    "tests"
 ]
addopts = "--verbose"
markers =[
    "integration"
]
norecursedirs = [
    "features",
    "build"
]
junit_logging = "all"
junit_log_passing_tests = true
junit_family="xunit2"
bdd_features_base_dir = "tests/features/"

[tool.pylint.MASTER]
init-hook="sys.path.append('.')"

[tool.cibuildwheel]
test-requires = "pytest"
test-command = "pytest {project}/tests"
manylinux-x86_64-image = "manylinux2014"
build-frontend = "build"
skip = [
    "cp36-*",
    "cp37-*",
    "pp*",
    "*-win32",
    "*-musllinux*",
    "*-manylinux_i686"
]
build-verbosity = 1
environment-pass = ["CONAN_COMPILER_LIBCXX", "CONAN_COMPILER_VERSION", "CONAN_USER_HOME"]

[tool.cibuildwheel.windows]
before-all = [
    'pip install wheel',
    'pip install -r requirements/requirements_conan.txt cmake ninja',
    'conan profile new default --detect --force',
    'conan config init',
    'conan config set general.revisions_enabled=1',
    'conan profile update settings.compiler.version=%CONAN_COMPILER_VERSION% default',
    'conan install ./ --build missing',
]
[tool.cibuildwheel.windows.environment]
CONAN_USER_HOME="$TEMP/conan"

[tool.cibuildwheel.macos]
before-all = [
    "pip3 install -r requirements/requirements_conan.txt cmake ninja",
    'conan profile new $ENVTMPDIR/.conan/profiles/default --detect --force',
    'conan config init',
    'conan config set general.revisions_enabled=1',
    'if [ -z \"$CONAN_COMPILER_VERSION\" ]; then : ; else conan profile update settings.compiler.version=$CONAN_COMPILER_VERSION default; fi',
    'mkdir -p $CONAN_BUILD_INFO_DIR',
    'conan install ./ --build missing --install-folder=$CONAN_BUILD_INFO_DIR'
]
environment-pass = ["CONAN_COMPILER_VERSION", "CONAN_USER_HOME"]
repair-wheel-command = [
    "delocate-wheel --version",
    "delocate-listdeps {wheel}",
    "delocate-wheel --require-archs {delocate_archs} -w {dest_dir} -v {wheel}",
]

[tool.cibuildwheel.macos.environment]
ENVTMPDIR="/tmp/ciwheelbuilder/uiucprescon_ocr"
CONAN_USER_HOME="/tmp/ciwheelbuilder/uiucprescon_ocr"
CONAN_DEFAULT_PROFILE_PATH="/tmp/ciwheelbuilder/uiucprescon_ocr/.conan/profiles/default"
CONAN_BUILD_INFO_DIR="/tmp/ciwheelbuilder/uiucprescon_ocr/build/"


[tool.cibuildwheel.linux]
repair-wheel-command = "auditwheel repair -w {dest_dir} {wheel}"
before-all = [
    'cc --version', 'cc -dumpfullversion -dumpversion',
    'pip3 install -r requirements/requirements_conan.txt cmake ninja',
    'conan profile new /tmp/ciwheelbuilder/uiucprescon_ocr/.conan/profiles/default --detect',
    'conan config set general.revisions_enabled=1',
    'if [ -z \"$CONAN_COMPILER_LIBCXX\" ]; then : ; else conan profile update settings.compiler.libcxx=$CONAN_COMPILER_LIBCXX default; fi',
    'if [ -z \"$CONAN_COMPILER_VERSION\" ]; then : ; else conan profile update settings.compiler.version=$CONAN_COMPILER_VERSION default; fi',
    "conan profile show default",
    "conan install ./ --build missing",

]
[tool.cibuildwheel.linux.environment]
CONAN_USER_HOME="/tmp/ciwheelbuilder/uiucprescon_ocr"
CONAN_DEFAULT_PROFILE_PATH="/tmp/ciwheelbuilder/uiucprescon_ocr/.conan/profiles/default"
CONAN_BUILD_INFO_DIR="/tmp/ciwheelbuilder/uiucprescon_ocr/build/"
PYTHONFAULTHANDLER="True"
CONAN_COMPILER_LIBCXX="libstdc++11"
#
[localbuilder]
conanfile = 'conanfile.py'

#[localbuilder.linux]
#conan_options = ['tesseract:shared=True']
[localbuilder.win32]
conan_options = ['tesseract:shared=True']

[tool.pylint]
extension-pkg-allow-list="uiucprescon.ocr.tesseractwrap"
