[tox]
envlist = py3{10-14},py314t
min_version = 4.11

[testenv]
;package=wheel
pass_env =
    CONAN_USER_HOME
    SAMPLES_PATH
    TESSDATA_PREFIX
labels =
    test
dependency_groups = test
uv_sync_flags = --no-editable
commands =
    {env_bin_dir}{/}pytest {posargs} --basetemp={envtmpdir}

[testenv:docs]
labels =
    docs
dependency_groups = docs
commands=
    sphinx-build -W -b html -d {temp_dir}/doctrees docs/source  {temp_dir}/dist/docs/html

[testenv:doctest]
depends = docs
labels =
    docs
dependency_groups = docs
commands=
    sphinx-build -b doctest  -d {temp_dir}/doctrees docs/source {temp_dir}/build/doctest {posargs}

[testenv:readelf]
platform = linux
allowlist_externals=
    readelf
    find
commands =
    find {envsitepackagesdir}/uiucprescon/ocr -maxdepth 1 -name "*.so"  -type f -exec readelf -d \{\} ;

[testenv:mypy]
labels =
    static-analysis
    type-checking
dependency_groups = type-checking
skip_install=True
setenv =
    MYPY_CACHE_DIR = {temp_dir}/.mypy_cache
    MYPYPATH = {temp_dir}/mypystubs
commands =
    stubgen -p uiucprescon.ocr -o {temp_dir}/mypystubs
    mypy {posargs: -p uiucprescon.ocr}

[testenv:flake8]
description = check the code style
labels =
    static-analysis
    code-style
    linting
dependency_groups = code-style
skip_install=True
commands = flake8 {posargs: src}

[testenv:pylint]
description = check the code style
labels =
    static-analysis
    linting
dependency_groups = linting
skip_install=True
commands =  pylint {posargs: src}

[testenv:ruff]
labels =
    linting
    code-style
    static-analysis
skip_install = true
dependency_groups = linting
commands =
    ruff check {posargs: {toxinidir}/src}

[testenv:pydocstyle]
labels =
    static-analysis
    linting
    code-style
    docs
skip_install = true
dependency_groups = code-style
commands =
    pydocstyle {posargs: {toxinidir}/src}

[testenv:bandit]
labels =
    static-analysis
    security
skip_install = true
dependency_groups = security
commands =
    bandit {posargs: --recursive {toxinidir}/src}
