name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macOS-11]
        include:
          - os: macOS-11
            compiler_version: 13
          - os: ubuntu-20.04
            compiler_version: 10

    steps:
      - uses: actions/checkout@v3

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.10.2

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
           CONAN_COMPILER_VERSION: ${{ matrix.compiler_version }}
        #   CIBW_SOME_OPTION: value
